### ISSUE TITLE
g++: can't make tuple of atomics

### ISSUE THREAD

**Issue by alextsui05** [acgetchell/CDT-plusplus#14]
I can't build CDT-plusplus because `move_tuple` is being defined as a tuple of atomics, but atomics have their copy constructors deleted. Here's a minimal executable example that fails to compile with g++5:

https://gist.github.com/alextsui05/10092baa46ced7b6c6d4

**Comment by acgetchell** [comment]
Okay, I'm looking at gcc issues. It compiles fine on clang ...

**Comment by acgetchell** [comment]
I believe https://github.com/acgetchell/CDT-plusplus/commit/33a522ea1f8db373612d7133c28beff1d8820b4c fixes this, though I still have to sort out GMock/GTest linker issues.

**Comment by acgetchell** [comment]
Yes, https://github.com/acgetchell/CDT-plusplus/commit/b24b8057cae673f0ca7eaae589c8a5d19c6e2f49 builds correctly with gcc5, GoogleTest, and GoogleMock. Now to fix clang.
