### ISSUE TITLE
gxn1710: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by gxn1710** [acgetchell/CDT-plusplus#22]
Hello everyone! My name is Gaurav and I am a second year engineering student with interests in applied math, physics, and computer science. Although I don't have specific experience with CGAL, I am interested in and understand the mathematical and algorithmic context of this project. So far, I am looking into coding the shortest paths algorithms. Given my interests, are there any specific tasks that you guys recommend that I contribute to?<p><br><blockquote>This issue was created by @gxn1710 via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by gxn1710** [comment]
Can I get more context on the shortest paths algorithms? What exactly do the "nodes" in the graph represent? Similarly, what do the edges and the edge weights represent? Thanks.

**Comment by acgetchell** [comment]
Thanks Guarav for your contribution. I'm looking forward to many more!
