### ISSUE TITLE
Prince kumar: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by prince006** [acgetchell/CDT-plusplus#3]
i have done some projects in C++, so having some knowledge with help this project to make it successful.
Thank you<p><br><blockquote>This issue was created by @prince006 via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acgetchell** [comment]
Awesome @prince006 ! You may want to look at http://cgal.org for documentation, as well as join the CGAL mailing list. This project does a lot of work with CGAL (hence the name), so understanding how CGAL works and is written will be essential.

![welcome](https://cloud.githubusercontent.com/assets/434849/5888222/36c9b1b4-a3ab-11e4-856c-0dfa293961a5.jpg)

**Comment by prince006** [comment]
Hey acgetchell..
will you provide more info on CGAL?

**Comment by prince006** [comment]
and where is CGAL mailing list?

**Comment by acgetchell** [comment]
Documentation on CGAL and links to the mailing list are provided on the main CGAL homepage linked above.

**Comment by acgetchell** [comment]
Sorry, should have been more helpful. CGAL is enormous. CDT has lots of literature.

The first thing to read is the 3D Delaunay triangulation and the 3D Triangulation Data Structure. 

http://doc.cgal.org/latest/Triangulation_3/index.html#Chapter_3D_Triangulations

http://doc.cgal.org/latest/TDS_3/classTriangulationDataStructure__3.html

From there, you can look over the dD Delaunay triangulations and Convex Hulls. 

http://doc.cgal.org/latest/Convex_hull_d/index.html#Chapter_dD_Convex_Hulls_and_Delaunay_Triangulations

My latest commits involve trying to implement the 3D moves on 2+1 space times, which is described on pp. 21-22 here:

http://arxiv.org/pdf/hep-th/0105267v1.pdf

Hope that helps!

**Comment by acgetchell** [comment]
I think all of the questions have been answered here, so I'm going to close this issue.
