### ISSUE TITLE
Parssing args error

### ISSUE THREAD

**Issue by ixxra** [acgetchell/CDT-plusplus#8]
I don't know why, but I had to modify command parssing in order to get *cdt* working.

I disabled long options to allow parssing args successfully, but certainly, this is not the best way to make it work.

Someone having similar problems?

**Comment by acgetchell** [comment]
Hmmm. Command parsing is handled by [docopt.cpp](https://github.com/docopt/docopt.cpp); do you have issues running the tests?

**Comment by ixxra** [comment]
I couldn't install gmock on arch.

**Comment by acgetchell** [comment]
Look over [install-linux.sh](https://github.com/acgetchell/CDT-plusplus/blob/master/install-linux.sh), that has explicit instructions.

**Comment by acgetchell** [comment]
I'm going to close this out now, feel free to ask further questions.

**Comment by ixxra** [comment]
I could use CDT, so I was unaware the issue was yet open.

thanks for letting me know,
